// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palettes.Data;

#nullable disable

namespace Palettes.Data.Migrations
{
    [DbContext(typeof(PalettesDbContext))]
    [Migration("20250404084415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palettes.Core.Models.Palette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentClr")
                        .HasColumnType("text");

                    b.Property<string>("BaseClr")
                        .HasColumnType("text");

                    b.Property<string>("HoverClr")
                        .HasColumnType("text");

                    b.Property<string>("LineClr")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryTextClr")
                        .HasColumnType("text");

                    b.Property<string>("SectionClr")
                        .HasColumnType("text");

                    b.Property<string>("ShadowClr")
                        .HasColumnType("text");

                    b.Property<string>("TextClr")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Palettes");
                });
#pragma warning restore 612, 618
        }
    }
}
